id: P40874087
initial_creation_type: input
source_metadata:
  title: Bodhicittavivaraṇa-fragments
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Buddhist
  data entry: Richard Mahoney
  contribution to GRETIL: Richard Mahoney
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:17:31.312277'
last_modified_at: '2022-03-09T15:17:31.312291'
